### ISSUE TITLE
flutter 3.10.2 conflict

### ISSUE THREAD

**Issue by getong** [hasanmhallak/date_picker#2]
flutter 3.10.2
pubspec.yml
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  date_picker_plus: ^1.0.2
```

compile error:
```
Because date_picker_plus 1.0.2 depends on intl ^0.17.0 and no versions of date_picker_plus match >1.0.2
  <2.0.0, date_picker_plus ^1.0.2 requires intl ^0.17.0.
So, because date_picker_example depends on both intl ^0.18.1 and date_picker_plus ^1.0.2, version solving
  failed.
```

**Comment by hasanmhallak** [comment]
hey @getong you can use v1.1.0 now, it will fix this issue.

**Comment by getong** [comment]
pubspec.yaml
```
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  date_picker_plus: ^1.1.0
```

compile error
```
Because date_picker_example depends on flutter_localizations from sdk which depends on intl 0.18.0, intl
  0.18.0 is required.
So, because date_picker_example depends on intl ^0.18.1, version solving failed.
```

But  intl: 0.18.0  is ok, but current intl version is 0.18.1.
